In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
!wget https://www.takakura.com/Kyoto_data/new_data201704/2015/201512.zip

--2024-03-28 07:12:38--  https://www.takakura.com/Kyoto_data/new_data201704/2015/201512.zip
Resolving www.takakura.com (www.takakura.com)... 150.100.120.5, 2001:2f8:3a:2100::5
Connecting to www.takakura.com (www.takakura.com)|150.100.120.5|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 181366761 (173M) [application/zip]
Saving to: ‘201512.zip’

201512.zip          100%[===================>] 172.96M  21.6MB/s    in 9.0s    

2024-03-28 07:12:48 (19.3 MB/s) - ‘201512.zip’ saved [181366761/181366761]



In [3]:
!unzip /content/201512.zip

Archive:  /content/201512.zip
   creating: Kyoto2016/2015/12/
  inflating: Kyoto2016/2015/12/20151211.txt  
  inflating: Kyoto2016/2015/12/20151209.txt  
  inflating: Kyoto2016/2015/12/20151223.txt  
  inflating: Kyoto2016/2015/12/20151215.txt  
  inflating: Kyoto2016/2015/12/20151201.txt  
  inflating: Kyoto2016/2015/12/20151217.txt  
  inflating: Kyoto2016/2015/12/20151207.txt  
  inflating: Kyoto2016/2015/12/20151219.txt  
  inflating: Kyoto2016/2015/12/20151229.txt  
  inflating: Kyoto2016/2015/12/20151208.txt  
  inflating: Kyoto2016/2015/12/20151205.txt  
  inflating: Kyoto2016/2015/12/20151222.txt  
  inflating: Kyoto2016/2015/12/20151227.txt  
  inflating: Kyoto2016/2015/12/20151216.txt  
  inflating: Kyoto2016/2015/12/20151225.txt  
  inflating: Kyoto2016/2015/12/20151203.txt  
  inflating: Kyoto2016/2015/12/20151224.txt  
  inflating: Kyoto2016/2015/12/20151214.txt  
  inflating: Kyoto2016/2015/12/20151228.txt  
  inflating: Kyoto2016/2015/12/20151213.txt  
  inflating: Kyoto

In [4]:
df = pd.read_csv("/content/Kyoto2016/2015/12/20151209.txt",
                 names= [
                     "duration",
                     "service",
                     "source_bytes",
                     "destination",
                     "count",
                     "same_srv_rate",
                     "serror_rate",
                     "srv_serror_rate",
                     "dst_host_count",
                     "dst_host_srv_count",
                     "dst_host_same_src_port_rate",
                     "dst_host_serror_rate",
                     "dst_host_srv_error_rate",
                     "flag",
                     "ids_label",
                     "malware_detection_label",
                     "ashula_detection",
                     "label",
                     "source_ip_address",
                     "source_port",
                     "destination_ip_address",
                     "destination_port_number",
                     "start_time",
                     "protocol"
                 ],
                 delimiter="\t")
df.head()

# df = df[:100000]

duration service  source_bytes  destination  count  same_srv_rate  \
0  0.000000   other             0            0      0            0.0   
1  2.999947   other             0            0      1            1.0   
2  0.000000   other             0            0      0            0.0   
3  0.000060   other             0            0      0            0.0   
4  0.000074   other             0            0      1            1.0   

   serror_rate  srv_serror_rate  dst_host_count  dst_host_srv_count  ...  \
0          0.0             0.80               1                   5  ...   
1          1.0             0.83               1                   1  ...   
2          0.0             1.00               1                   2  ...   
3          0.0             1.00               1                   3  ...   
4          0.0             0.75               2                   4  ...   

   ids_label  malware_detection_label  ashula_detection label  \
0          0                        0                 0    -1   
1          0                        0                 0    -1   
2          0                        0                 0    -1   
3          0                        0                 0    -1   
4          0                        0                 0    -1   

                         source_ip_address source_port  \
0  fdbd:f115:35b2:59be:2582:1994:0326:1ee0       64975   
1  fdbd:f115:35b2:c672:061c:037a:0303:0182       35636   
2  fdbd:f115:35b2:7485:21c5:1942:4ff5:3705       10984   
3  fdbd:f115:35b2:072d:4ca5:1512:2bd2:030c       65104   
4  fdbd:f115:35b2:072d:4ca5:1512:2bd2:030c       65104   

                    destination_ip_address  destination_port_number  \
0  fdbd:f115:35b2:a440:7d94:278d:61f4:31d3                       25   
1  fdbd:f115:35b2:1f77:7af1:00c2:5f0d:3492                       23   
2  fdbd:f115:35b2:fd20:7ddf:279b:609d:41cd                      445   
3  fdbd:f115:35b2:c152:7d74:2701:61f4:35ec                       25   
4  fdbd:f115:35b2:c152:7d74:2701:61f4:35ec                       25   

  start_time  protocol  
0   00:00:00       tcp  
1   00:00:00       tcp  
2   00:00:01       tcp  
3   00:00:01       tcp  
4   00:00:01       tcp  

[5 rows x 24 columns]

In [5]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

# Iterate through each categorical column and encode it
for col in df.select_dtypes(include=['object']).columns:
    df[col] = label_encoder.fit_transform(df[col])

In [6]:
df.head()

duration  service  source_bytes  destination  count  same_srv_rate  \
0  0.000000        3             0            0      0            0.0   
1  2.999947        3             0            0      1            1.0   
2  0.000000        3             0            0      0            0.0   
3  0.000060        3             0            0      0            0.0   
4  0.000074        3             0            0      1            1.0   

   serror_rate  srv_serror_rate  dst_host_count  dst_host_srv_count  ...  \
0          0.0             0.80               1                   5  ...   
1          1.0             0.83               1                   1  ...   
2          0.0             1.00               1                   2  ...   
3          0.0             1.00               1                   3  ...   
4          0.0             0.75               2                   4  ...   

   ids_label  malware_detection_label  ashula_detection  label  \
0          0                        0                 0     -1   
1          0                        0                 0     -1   
2          0                        0                 0     -1   
3          0                        0                 0     -1   
4          0                        0                 0     -1   

   source_ip_address  source_port  destination_ip_address  \
0              12261        64975                     822   
1              27193        35636                     166   
2              15860        10984                    1274   
3                990        65104                     957   
4                990        65104                     957   

   destination_port_number  start_time  protocol  
0                       25           0         1  
1                       23           0         1  
2                      445           1         1  
3                       25           1         1  
4                       25           1         1  

[5 rows x 24 columns]

In [7]:
dataset = df

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[0.000000e+00 3.000000e+00 0.000000e+00 ... 8.220000e+02 2.500000e+01
  0.000000e+00]
 [2.999947e+00 3.000000e+00 0.000000e+00 ... 1.660000e+02 2.300000e+01
  0.000000e+00]
 [0.000000e+00 3.000000e+00 0.000000e+00 ... 1.274000e+03 4.450000e+02
  1.000000e+00]
 ...
 [0.000000e+00 3.000000e+00 0.000000e+00 ... 8.220000e+02 2.500000e+01
  6.461500e+04]
 [1.040000e-04 1.000000e+00 5.600000e+01 ... 3.170000e+02 5.300000e+01
  6.461500e+04]
 [1.390000e-04 1.000000e+00 4.700000e+01 ... 3.170000e+02 5.300000e+01
  6.461500e+04]]
[1 1 1 ... 1 2 2]


In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:68])
X[:, 1:68] = imputer.transform(X[:, 1:68])
print(X)

[[0.000000e+00 3.000000e+00 0.000000e+00 ... 8.220000e+02 2.500000e+01
  0.000000e+00]
 [2.999947e+00 3.000000e+00 0.000000e+00 ... 1.660000e+02 2.300000e+01
  0.000000e+00]
 [0.000000e+00 3.000000e+00 0.000000e+00 ... 1.274000e+03 4.450000e+02
  1.000000e+00]
 ...
 [0.000000e+00 3.000000e+00 0.000000e+00 ... 8.220000e+02 2.500000e+01
  6.461500e+04]
 [1.040000e-04 1.000000e+00 5.600000e+01 ... 3.170000e+02 5.300000e+01
  6.461500e+04]
 [1.390000e-04 1.000000e+00 4.700000e+01 ... 3.170000e+02 5.300000e+01
  6.461500e+04]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[1 1 1 ... 1 2 2]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [11]:
def get_test_split( num):
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = num, random_state = 0)

  from sklearn.preprocessing import StandardScaler
  sc = StandardScaler()
  X_train = sc.fit_transform(X_train)
  X_test = sc.fit_transform(X_test)

  return X_train, X_test, y_train, y_test


In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
import lightgbm as lgb


for i in [0.2,0.3,0.4]:
  X_train, X_test, y_train, y_test = get_test_split(i)

  print("for split ", i)

  clf = lgb.LGBMClassifier()
  clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  accuracy = accuracy_score(y_test, y_pred)
  print("LGBM Accuracy:", accuracy)

  from sklearn.svm import LinearSVC

  clf = LinearSVC()
  clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  accuracy = accuracy_score(y_test, y_pred)
  print("LinearSVC Accuracy:", accuracy)

  from sklearn.neural_network import MLPClassifier

  clf = MLPClassifier()
  clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  accuracy = accuracy_score(y_test, y_pred)
  print("MLP Accuracy:", accuracy)

  from sklearn.naive_bayes import GaussianNB
  clf = GaussianNB()
  clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  accuracy = accuracy_score(y_test, y_pred)
  print("NB Accuracy:", accuracy)

  from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

  clf = QuadraticDiscriminantAnalysis()
  clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  accuracy = accuracy_score(y_test, y_pred)
  print("QDA Accuracy:", accuracy)

  from sklearn.tree import DecisionTreeClassifier

  clf = DecisionTreeClassifier()
  clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  accuracy = accuracy_score(y_test, y_pred)
  print("DecisionTree Accuracy:", accuracy)

  from sklearn.ensemble import GradientBoostingClassifier

  clf = GradientBoostingClassifier()
  clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  accuracy = accuracy_score(y_test, y_pred)
  print("GradientBoosting Accuracy:", accuracy)


  from sklearn.ensemble import RandomForestClassifier

  clf = RandomForestClassifier()
  clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  accuracy = accuracy_score(y_test, y_pred)
  print("RandomForest Accuracy:", accuracy)

  import xgboost as xgb

  clf = xgb.XGBClassifier()
  clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  accuracy = accuracy_score(y_test, y_pred)
  print("XGB Accuracy:", accuracy)


  from sklearn.ensemble import AdaBoostClassifier

  clf = AdaBoostClassifier()
  clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  accuracy = accuracy_score(y_test, y_pred)
  print("ADA Accuracy:", accuracy)

  from sklearn.neighbors import KNeighborsClassifier

  clf = KNeighborsClassifier()
  clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  accuracy = accuracy_score(y_test, y_pred)
  print("KNN Accuracy:", accuracy)

  from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

  clf = LinearDiscriminantAnalysis()
  clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  accuracy = accuracy_score(y_test, y_pred)
  print("LDA Accuracy:", accuracy)

  from sklearn.linear_model import LogisticRegression

  clf = LogisticRegression()
  clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  accuracy = accuracy_score(y_test, y_pred)
  print("LogisticRegression Accuracy:", accuracy)

  from sklearn.svm import SVC


  classifier = SVC(kernel='rbf', probability=True, random_state=0)
  classifier.fit(X_train, y_train)
  y_pred = classifier.predict(X_test)
  print("SVC Accuracy:", accuracy_score(y_test, y_pred))

for split  0.2
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.036873 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2767
[LightGBM] [Info] Number of data points in the train set: 189736, number of used features: 23
[LightGBM] [Info] Start training from score -4.368084
[LightGBM] [Info] Start training from score -0.454673
[LightGBM] [Info] Start training from score -1.042225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
LGBM Accuracy: 0.9494033815406671


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC Accuracy: 0.9190454104650673
MLP Accuracy: 0.9766201458869166
NB Accuracy: 0.6324577307416621


/usr/local/lib/python3.10/dist-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


QDA Accuracy: 0.632436648817304
DecisionTree Accuracy: 0.8667411561327318
GradientBoosting Accuracy: 0.9542311422186617
RandomForest Accuracy: 0.9530716363789686
XGB Accuracy: 0.8700931821056626
ADA Accuracy: 0.632436648817304
KNN Accuracy: 0.9768942109035713
LDA Accuracy: 0.9102331660834001


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression Accuracy: 0.9172534468946325
SVC Accuracy: 0.972635662183244
for split  0.3
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.030968 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2749
[LightGBM] [Info] Number of data points in the train set: 166019, number of used features: 23
[LightGBM] [Info] Start training from score -4.374938
[LightGBM] [Info] Start training from score -0.454112
[LightGBM] [Info] Start training from score -1.042990
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
LGBM Accuracy: 0.951300754732892


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC Accuracy: 0.9180475327121193
MLP Accuracy: 0.9758260600694298
NB Accuracy: 0.6323593484279911


/usr/local/lib/python3.10/dist-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


QDA Accuracy: 0.6323452938117524
DecisionTree Accuracy: 0.8877738893339517
GradientBoosting Accuracy: 0.955756068080561
RandomForest Accuracy: 0.9578502059001279
XGB Accuracy: 0.9088558136920072
ADA Accuracy: 0.6323452938117524
KNN Accuracy: 0.9762758077890683
LDA Accuracy: 0.9092071790979748


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression Accuracy: 0.9165015249258619


In [16]:
import lightgbm as lgb

X_train, X_test, y_train, y_test = get_test_split(0.4)

clf = lgb.LGBMClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.039011 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2728
[LightGBM] [Info] Number of data points in the train set: 142302, number of used features: 23
[LightGBM] [Info] Start training from score -4.374619
[LightGBM] [Info] Start training from score -0.453375
[LightGBM] [Info] Start training from score -1.044330
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Accuracy: 0.9518699666905596


In [17]:
from sklearn.svm import LinearSVC

X_train, X_test, y_train, y_test = get_test_split(0.4)

clf = LinearSVC()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9172429059324535


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [18]:
from sklearn.neural_network import MLPClassifier
X_train, X_test, y_train, y_test = get_test_split(0.4)


clf = MLPClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9761247206645023


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

X_train, X_test, y_train, y_test = get_test_split(0.4)


from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

In [19]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

X_train, X_test, y_train, y_test = get_test_split(0.4)


clf = QuadraticDiscriminantAnalysis()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

/usr/local/lib/python3.10/dist-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


Accuracy: 0.6323101572711557


In [20]:
from sklearn.tree import DecisionTreeClassifier

X_train, X_test, y_train, y_test = get_test_split(0.4)


clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9358687861027954


In [26]:
from sklearn.ensemble import GradientBoostingClassifier

X_train, X_test, y_train, y_test = get_test_split(0.4)


clf = GradientBoostingClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9550322553442678


In [21]:
from sklearn.ensemble import RandomForestClassifier

X_train, X_test, y_train, y_test = get_test_split(0.4)


clf = RandomForestClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9622949782856179


In [22]:
import xgboost as xgb

X_train, X_test, y_train, y_test = get_test_split(0.4)

clf = xgb.XGBClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9120778344647299


In [17]:
!pip install catboost

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.5/98.5 MB 9.3 MB/s eta 0:00:00


In [20]:
%%capture
from catboost import CatBoostClassifier


X_train, X_test, y_train, y_test = get_test_split(0.4)

clf = CatBoostClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


In [21]:
print("Accuracy:", accuracy)


Accuracy: 0.9595016233081756


In [27]:
from sklearn.ensemble import AdaBoostClassifier

X_train, X_test, y_train, y_test = get_test_split(0.4)

clf = AdaBoostClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.6323101572711557


In [14]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

clf = KNeighborsClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.8281717755196695


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

X_train, X_test, y_train, y_test = get_test_split(0.4)

clf = KNeighborsClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

In [29]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

X_train, X_test, y_train, y_test = get_test_split(0.4)

clf = LinearDiscriminantAnalysis()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9090736602437071


In [30]:
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = get_test_split(0.4)

clf = LogisticRegression()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.915925285660075


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [13]:
from sklearn.svm import SVC

X_train, X_test, y_train, y_test = get_test_split(0.4)

classifier = SVC(kernel='rbf', probability=True, random_state=0)
classifier.fit(X_train, y_train)


y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[ 1093   173     0]
 [    5 59692   289]
 [    0  2186 31430]]


0.9720348273390395

In [14]:
from sklearn.svm import SVC

X_train, X_test, y_train, y_test = get_test_split(0.3)

classifier = SVC(kernel='rbf', probability=True, random_state=0)
classifier.fit(X_train, y_train)


y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[  842   126     0]
 [    3 44770   219]
 [    0  1599 23592]]


0.972635662183244